# Generated by Django 2.2.6 on 2020-03-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_items',
            field=models.PositiveIntegerField(default=0, verbose_name='total_items'),
            preserve_default=False,
        ),
    ]
